const createRoleSlice = (set) => ({
  isViewDashboard: true,
  isViewExecutions: true,
  isCreateExecution: true,
  isEditExecution: true,
  isDeleteExecution: true,
  isBulkLoadExecution: true,
  isLoadIndexBySedeExecution: true,
  isStateUpdatedExecution: true,
  isViewReport: true,
  isViewDataManagement: true,
  isCreateDataManagement: true,
  isEditDataManagement: true,
  isDeleteDataManagement: true,
  isBulkLoadInstitutionsManagement: true,
  isViewTool: true,
  isEditTool: true,
  isCreateTool1: true,
  isCreateTool2: true,
  isDeleteTool: true,
  isViewHelp: true,
  isViewConfiguration: true,
  isViewUserModule: true,
  permissionsByRole: (role) => {
    const SELECT_ROLE = {
      admin: () => set({ isViewConfiguration: true, isViewUserModule: true }),
      
      student: () =>
        set({
          isViewExecutions: false,
          isCreateExecution: false,
          isEditExecution: false,
          isDeleteExecution: false,
          isBulkLoadExecution: false,
          isLoadIndexBySedeExecution: false,
          isStateUpdatedExecution: false,
          isViewDataManagement: false,
          isCreateDataManagement: false,
          isEditDataManagement: false,
          isDeleteDataManagement: false,
          isBulkLoadInstitutionsManagement: false,
          isViewUserModule: true,
          isViewConfiguration: false,
        }),
      /*
      secretaria: () =>
        set({
          isCreateDataManagement: false,
          isEditDataManagement: false,
          isDeleteDataManagement: false,
          isBulkLoadInstitutionsManagement: false,
          isViewUserModule: false,
          isViewConfiguration: false,
        }),
      rector: () =>
        set({
          isCreateExecution: false,
          isEditExecution: false,
          isDeleteExecution: false,
          isBulkLoadExecution: false,
          isStateUpdatedExecution: false,
          isViewDataManagement: false,
          isCreateDataManagement: false,
          isEditDataManagement: false,
          isDeleteDataManagement: false,
          isBulkLoadInstitutionsManagement: false,
          isViewUserModule: false,
          isViewConfiguration: false,
        }),
      docente: () =>
        set({
          isViewExecutions: false,
          isCreateExecution: false,
          isEditExecution: false,
          isDeleteExecution: false,
          isBulkLoadExecution: false,
          isLoadIndexBySedeExecution: false,
          isStateUpdatedExecution: false,
          isViewDataManagement: false,
          isCreateDataManagement: false,
          isEditDataManagement: false,
          isDeleteDataManagement: false,
          isBulkLoadInstitutionsManagement: false,
          isEditTool: false,
          isDeleteTool: false,
          isViewUserModule: false,
          isViewConfiguration: false,
        }),
      encuestador: () =>
        set({
          isViewExecutions: false,
          isCreateExecution: false,
          isEditExecution: false,
          isDeleteExecution: false,
          isBulkLoadExecution: false,
          isLoadIndexBySedeExecution: false,
          isStateUpdatedExecution: false,
          isViewDataManagement: false,
          isCreateDataManagement: false,
          isEditDataManagement: false,
          isDeleteDataManagement: false,
          isBulkLoadInstitutionsManagement: false,
          isViewUserModule: false,
          isViewConfiguration: false,
        }),
    */

    };
 
    return SELECT_ROLE[role] ? SELECT_ROLE[role]() : null;
  },
  resetPermissions: () =>
    set({
      isViewDashboard: true,
      isViewExecutions: true,
      isCreateExecution: true,
      isEditExecution: true,
      isDeleteExecution: true,
      isBulkLoadExecution: true,
      isLoadIndexBySedeExecution: true,
      isStateUpdatedExecution: true,
      isViewReport: true,
      isViewDataManagement: true,
      isCreateDataManagement: true,
      isEditDataManagement: true,
      isDeleteDataManagement: true,
      isBulkLoadInstitutionsManagement: true,
      isViewTool: true,
      isEditTool: true,
      isCreateTool1: true,
      isCreateTool2: true,
      isDeleteTool: true,
      isViewHelp: true,
      isViewUserModule: true,
      isViewConfiguration: true,
    }),
});

export default createRoleSlice;
