export const listTools = [
  {
    idTool: 1,
    year: 2022,
    execution: 'Ejecución 1',
    date_creation: '2022-06-08',
    date_modification: '2022-06-08',
    title: 'Formulario 1',
  },
  {
    idTool: 2,
    year: 2023,
    execution: 'Ejecución 2',
    date_creation: '2022-06-08',
    date_modification: '2022-06-08',
    title: 'Formulario 2',
  },
  {
    idTool: 3,
    year: 2024,
    execution: 'Ejecución 3',
    date_creation: '2022-06-08',
    date_modification: '2022-06-08',
    title: 'Formulario 3',
  },
  {
    idTool: 4,
    year: 2025,
    execution: 'Ejecución 4',
    date_creation: '2022-06-08',
    date_modification: '2022-06-08',
    title: 'Formulario 4',
  },
  {
    idTool: 5,
    year: 2026,
    execution: 'Ejecución 5',
    date_creation: '2022-06-08',
    date_modification: '2022-06-08',
    title: 'Formulario 5',
  },
];

export const listQuestionForm1 = [
  {
    title: 'Sección A',
    id: 'A.1.1',
    idIndex: 0,
    text: 'La institución educativa admite a toda la población del sector sin discriminación de raza, cultura, género, ideología, credo, preferencia sexual, condición socioeconómica, o situaciones de vulnerabilidad, como: desplazamiento, violencia, y analfabetismo, entre otros.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.1.1' },
      { id: 3, name: 'Casi siempre', quest: 'A.1.1' },
      { id: 2, name: 'Algunas veces', quest: 'A.1.1' },
      { id: 1, name: 'No sé', quest: 'A.1.1' },
      { id: 0, name: 'No se hace', quest: 'A.1.1' },
    ],
  },
  {
    id: 'A.1.2',
    idIndex: 1,
    text: 'Toda la población que ingresa a la institución educativa recibe una atención que garantiza el aprendizaje, la participación, la convivencia y el avance de un grado a otro, preparándola para la vida y el trabajo.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.1.2' },
      { id: 3, name: 'Casi siempre', quest: 'A.1.2' },
      { id: 2, name: 'Algunas veces', quest: 'A.1.2' },
      { id: 1, name: 'No sé', quest: 'A.1.2' },
      { id: 0, name: 'No se hace', quest: 'A.1.2' },
    ],
  },
  {
    id: 'A.1.3',
    idIndex: 2,
    text: 'La institución invita a la comunidad educativa a conocer y desarrollar actividades centradas en el respeto a la diferencia que faciliten el aprendizaje, la participación y la convivencia de toda la población.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.1.3' },
      { id: 3, name: 'Casi siempre', quest: 'A.1.3' },
      { id: 2, name: 'Algunas veces', quest: 'A.1.3' },
      { id: 1, name: 'No sé', quest: 'A.1.3' },
      { id: 0, name: 'No se hace', quest: 'A.1.3' },
    ],
  },
  {
    id: 'A.2.1',
    idIndex: 3,
    text: 'La institución tiene como política involucrar a su comunidad educativa en la evaluación y el diseño de propuestas para cualificar el aprendizaje, la participación, la convivencia y el respeto por la diferencia.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.2.1' },
      { id: 3, name: 'Casi siempre', quest: 'A.2.1' },
      { id: 2, name: 'Algunas veces', quest: 'A.2.1' },
      { id: 1, name: 'No sé', quest: 'A.2.1' },
      { id: 0, name: 'No se hace', quest: 'A.2.1' },
    ],
  },
  {
    id: 'A.2.2',
    idIndex: 4,
    text: 'La institución educativa articula en el PEI los planes, programas y proyectos nacionales, regionales y locales referidos a la atención a la diversidad.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.2.2' },
      { id: 3, name: 'Casi siempre', quest: 'A.2.2' },
      { id: 2, name: 'Algunas veces', quest: 'A.2.2' },
      { id: 1, name: 'No sé', quest: 'A.2.2' },
      { id: 0, name: 'No se hace', quest: 'A.2.2' },
    ],
  },
  {
    id: 'A.2.3',
    idIndex: 5,
    text: 'La institución educativa se caracteriza por dar una respuesta educativa plural, diversificada y flexible para satisfacer las necesidades de aprendizaje de todos sus estudiantes.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.2.3' },
      { id: 3, name: 'Casi siempre', quest: 'A.2.3' },
      { id: 2, name: 'Algunas veces', quest: 'A.2.3' },
      { id: 1, name: 'No sé', quest: 'A.2.3' },
      { id: 0, name: 'No se hace', quest: 'A.2.3' },
    ],
  },
  {
    id: 'A.2.4',
    idIndex: 6,
    text: 'La institución educativa utiliza los resultados del Índice de Inclusión para realizar acciones de mejoramiento.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.2.4' },
      { id: 3, name: 'Casi siempre', quest: 'A.2.4' },
      { id: 2, name: 'Algunas veces', quest: 'A.2.4' },
      { id: 1, name: 'No sé', quest: 'A.2.4' },
      { id: 0, name: 'No se hace', quest: 'A.2.4' },
    ],
  },
  {
    id: 'A.2.5',
    idIndex: 7,
    text: 'La institución educativa revisa periódicamente las acciones para la inclusión definidas en el plan de mejoramiento, analizando los resultados y el impacto de su gestión.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.2.5' },
      { id: 3, name: 'Casi siempre', quest: 'A.2.5' },
      { id: 2, name: 'Algunas veces', quest: 'A.2.5' },
      { id: 1, name: 'No sé', quest: 'A.2.5' },
      { id: 0, name: 'No se hace', quest: 'A.2.5' },
    ],
  },
  {
    id: 'A.3.1',
    idIndex: 8,
    text: 'En la institución educativa el Consejo Directivo define las políticas para la atención a la diversidad y responde por su divulgación y cumplimento.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.3.1' },
      { id: 3, name: 'Casi siempre', quest: 'A.3.1' },
      { id: 2, name: 'Algunas veces', quest: 'A.3.1' },
      { id: 1, name: 'No sé', quest: 'A.3.1' },
      { id: 0, name: 'No se hace', quest: 'A.3.1' },
    ],
  },
  {
    id: 'A.3.2',
    idIndex: 9,
    text: 'En la institución el Consejo Académico orienta la implementación de modelos educativos, didácticas flexibles y opciones de comunicación que permitan el acceso al currículo de todos los estudiantes.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.3.2' },
      { id: 3, name: 'Casi siempre', quest: 'A.3.2' },
      { id: 2, name: 'Algunas veces', quest: 'A.3.2' },
      { id: 1, name: 'No sé', quest: 'A.3.2' },
      { id: 0, name: 'No se hace', quest: 'A.3.2' },
    ],
  },
  {
    id: 'A.3.3',
    idIndex: 10,
    text: 'En la institución educativa el Comité de Evaluación y Promoción asesora a los docentes en el proceso de evaluación y promoción flexible para dar respuesta a las características personales, intereses, ritmos y estilos de aprendizaje de cada estudiante.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.3.3' },
      { id: 3, name: 'Casi siempre', quest: 'A.3.3' },
      { id: 2, name: 'Algunas veces', quest: 'A.3.3' },
      { id: 1, name: 'No sé', quest: 'A.3.3' },
      { id: 0, name: 'No se hace', quest: 'A.3.3' },
    ],
  },
  {
    id: 'A.3.4',
    idIndex: 11,
    text: 'En la institución el comité de convivencia asesora a la comunidad educativa en la implementación de estrategias y mecanismos para promover el respeto por la diversidad.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.3.4' },
      { id: 3, name: 'Casi siempre', quest: 'A.3.4' },
      { id: 2, name: 'Algunas veces', quest: 'A.3.4' },
      { id: 1, name: 'No sé', quest: 'A.3.4' },
      { id: 0, name: 'No se hace', quest: 'A.3.4' },
    ],
  },
  {
    id: 'A.3.5',
    idIndex: 12,
    text: 'En la institución educativa se realiza la elección del Consejo Estudiantil con la participación de todos los estudiantes sin discriminación alguna.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.3.5' },
      { id: 3, name: 'Casi siempre', quest: 'A.3.5' },
      { id: 2, name: 'Algunas veces', quest: 'A.3.5' },
      { id: 1, name: 'No sé', quest: 'A.3.5' },
      { id: 0, name: 'No se hace', quest: 'A.3.5' },
    ],
  },
  {
    id: 'A.3.6',
    idIndex: 13,
    text: 'En la institución educativa se realiza la elección del Personero con la participación de todos los estudiantes sin discriminación alguna.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.3.6' },
      { id: 3, name: 'Casi siempre', quest: 'A.3.6' },
      { id: 2, name: 'Algunas veces', quest: 'A.3.6' },
      { id: 1, name: 'No sé', quest: 'A.3.6' },
      { id: 0, name: 'No se hace', quest: 'A.3.6' },
    ],
  },
  {
    id: 'A.4.1',
    idIndex: 14,
    text: 'La institución educativa utiliza medios de comunicación eficientes y comprensibles para todos con el fin de dar a conocer sus procesos de gestión.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.4.1' },
      { id: 3, name: 'Casi siempre', quest: 'A.4.1' },
      { id: 2, name: 'Algunas veces', quest: 'A.4.1' },
      { id: 1, name: 'No sé', quest: 'A.4.1' },
      { id: 0, name: 'No se hace', quest: 'A.4.1' },
    ],
  },
  {
    id: 'A.4.2',
    idIndex: 15,
    text: 'En la institución los integrantes de la comunidad educativa colaboran entre si para facilitar el aprendizaje, la participación y la convivencia de todos.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.4.2' },
      { id: 3, name: 'Casi siempre', quest: 'A.4.2' },
      { id: 2, name: 'Algunas veces', quest: 'A.4.2' },
      { id: 1, name: 'No sé', quest: 'A.4.2' },
      { id: 0, name: 'No se hace', quest: 'A.4.2' },
    ],
  },
  {
    id: 'A.4.3',
    idIndex: 16,
    text: 'La institución desarrolla políticas de reconocimiento y estímulos a los integrantes de su comunidad educativa que lideren acciones inclusivas.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.4.3' },
      { id: 3, name: 'Casi siempre', quest: 'A.4.3' },
      { id: 2, name: 'Algunas veces', quest: 'A.4.3' },
      { id: 1, name: 'No sé', quest: 'A.4.3' },
      { id: 0, name: 'No se hace', quest: 'A.4.3' },
    ],
  },
  {
    id: 'A.4.4',
    idIndex: 17,
    text: 'La institución educativa realiza acciones para identificar y divulgar experiencias significativas que sirvan de modelo para la atención a la diversidad.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.4.4' },
      { id: 3, name: 'Casi siempre', quest: 'A.4.4' },
      { id: 2, name: 'Algunas veces', quest: 'A.4.4' },
      { id: 1, name: 'No sé', quest: 'A.4.4' },
      { id: 0, name: 'No se hace', quest: 'A.4.4' },
    ],
  },
  {
    id: 'A.5.1',
    idIndex: 18,
    text: 'En la institución las familias y estudiantes se sienten orgullosos de pertenecer a una comunidad educativa donde se promueve el respeto y valoración por la diversidad.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.5.1' },
      { id: 3, name: 'Casi siempre', quest: 'A.5.1' },
      { id: 2, name: 'Algunas veces', quest: 'A.5.1' },
      { id: 1, name: 'No sé', quest: 'A.5.1' },
      { id: 0, name: 'No se hace', quest: 'A.5.1' },
    ],
  },
  {
    id: 'A.5.2',
    idIndex: 19,
    text: 'La institución educativa realiza acciones para que todas las personas puedan desplazarse sin dificultad por sus instalaciones.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.5.2' },
      { id: 3, name: 'Casi siempre', quest: 'A.5.2' },
      { id: 2, name: 'Algunas veces', quest: 'A.5.2' },
      { id: 1, name: 'No sé', quest: 'A.5.2' },
      { id: 0, name: 'No se hace', quest: 'A.5.2' },
    ],
  },
  {
    id: 'A.5.3',
    idIndex: 20,
    text: 'La institución educativa explica a estudiantes y familias sus características, funcionamiento y normas de convivencia para que todos se sientan bienvenidos.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.5.3' },
      { id: 3, name: 'Casi siempre', quest: 'A.5.3' },
      { id: 2, name: 'Algunas veces', quest: 'A.5.3' },
      { id: 1, name: 'No sé', quest: 'A.5.3' },
      { id: 0, name: 'No se hace', quest: 'A.5.3' },
    ],
  },
  {
    id: 'A.5.4',
    idIndex: 21,
    text: 'La institución educativa realiza acciones para que los estudiantes se motiven por aprender teniendo en cuenta sus habilidades e intereses.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.5.4' },
      { id: 3, name: 'Casi siempre', quest: 'A.5.4' },
      { id: 2, name: 'Algunas veces', quest: 'A.5.4' },
      { id: 1, name: 'No sé', quest: 'A.5.4' },
      { id: 0, name: 'No se hace', quest: 'A.5.4' },
    ],
  },
  {
    id: 'A.5.5',
    idIndex: 22,
    text: 'En la institución educativa el manual de convivencia orienta y promueve el respeto y valoración de la diversidad que se presenta en su comunidad.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.5.5' },
      { id: 3, name: 'Casi siempre', quest: 'A.5.5' },
      { id: 2, name: 'Algunas veces', quest: 'A.5.5' },
      { id: 1, name: 'No sé', quest: 'A.5.5' },
      { id: 0, name: 'No se hace', quest: 'A.5.5' },
    ],
  },
  {
    id: 'A.5.6',
    idIndex: 23,
    text: 'En la institución educativa todos los estudiantes tienen la oportunidad de participar en actividades complementarias y extracurriculares que posibilitan el desarrollo de habilidades e intereses.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.5.6' },
      { id: 3, name: 'Casi siempre', quest: 'A.5.6' },
      { id: 2, name: 'Algunas veces', quest: 'A.5.6' },
      { id: 1, name: 'No sé', quest: 'A.5.6' },
      { id: 0, name: 'No se hace', quest: 'A.5.6' },
    ],
  },
  {
    id: 'A.5.7',
    idIndex: 24,
    text: 'En la institución educativa los servicios de bienestar se ofrecen a los estudiantes que más lo requieren.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.5.7' },
      { id: 3, name: 'Casi siempre', quest: 'A.5.7' },
      { id: 2, name: 'Algunas veces', quest: 'A.5.7' },
      { id: 1, name: 'No sé', quest: 'A.5.7' },
      { id: 0, name: 'No se hace', quest: 'A.5.7' },
    ],
  },
  {
    id: 'A.5.8',
    idIndex: 25,
    text: 'En la institución educativa cuando los estudiantes tienen problemas se les escucha, se les ayuda a solucionarlos y se les enseña a mejorar su comportamiento.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.5.8' },
      { id: 3, name: 'Casi siempre', quest: 'A.5.8' },
      { id: 2, name: 'Algunas veces', quest: 'A.5.8' },
      { id: 1, name: 'No sé', quest: 'A.5.8' },
      { id: 0, name: 'No se hace', quest: 'A.5.8' },
    ],
  },
  {
    id: 'A.6.1',
    idIndex: 26,
    text: 'La institución educativa desarrolla estrategias para conocer el entorno familiar de los estudiantes con el fin de apoyarlos en la eliminación de barreras para el aprendizaje, la participación y la convivencia.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.6.1' },
      { id: 3, name: 'Casi siempre', quest: 'A.6.1' },
      { id: 2, name: 'Algunas veces', quest: 'A.6.1' },
      { id: 1, name: 'No sé', quest: 'A.6.1' },
      { id: 0, name: 'No se hace', quest: 'A.6.1' },
    ],
  },
  {
    id: 'A.6.2',
    idIndex: 27,
    text: 'La institución educativa desarrolla estrategias que le permiten vincularse a redes locales y regionales de la política social.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.6.2' },
      { id: 3, name: 'Casi siempre', quest: 'A.6.2' },
      { id: 2, name: 'Algunas veces', quest: 'A.6.2' },
      { id: 1, name: 'No sé', quest: 'A.6.2' },
      { id: 0, name: 'No se hace', quest: 'A.6.2' },
    ],
  },
  {
    id: 'A.6.3',
    idIndex: 28,
    text: 'La institución educativa intercambia recursos y servicios con otras instituciones para fortalecer el desarrollo de acciones inclusivas.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.6.3' },
      { id: 3, name: 'Casi siempre', quest: 'A.6.3' },
      { id: 2, name: 'Algunas veces', quest: 'A.6.3' },
      { id: 1, name: 'No sé', quest: 'A.6.3' },
      { id: 0, name: 'No se hace', quest: 'A.6.3' },
    ],
  },
  {
    id: 'A.6.4',
    idIndex: 29,
    text: 'La institución educativa establece alianzas con el sector productivo para fortalecer la propuesta educativa inclusiva y la proyección de los estudiantes al mundo laboral.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.6.4' },
      { id: 3, name: 'Casi siempre', quest: 'A.6.4' },
      { id: 2, name: 'Algunas veces', quest: 'A.6.4' },
      { id: 1, name: 'No sé', quest: 'A.6.4' },
      { id: 0, name: 'No se hace', quest: 'A.6.4' },
    ],
  },
  {
    title: 'Sección B',
    id: 'B.1.1',
    idIndex: 30,
    text: 'La institución educativa revisa permanentemente su plan de estudios para realizar los ajustes pertinentes que permitan hacerlo accesible a todos los estudiantes.',
    options: [
      { id: 4, name: 'Siempre', quest: 'B.1.1' },
      { id: 3, name: 'Casi siempre', quest: 'B.1.1' },
      { id: 2, name: 'Algunas veces', quest: 'B.1.1' },
      { id: 1, name: 'No sé', quest: 'B.1.1' },
      { id: 0, name: 'No se hace', quest: 'B.1.1' },
    ],
  },
  {
    id: 'B.1.2',
    idIndex: 31,
    text: 'En la institución educativa el enfoque metodológico permite que cada estudiante aprenda colaborativamente, teniendo en cuenta sus características, estilos y ritmos de aprendizaje.',
    options: [
      { id: 4, name: 'Siempre', quest: 'B.1.2' },
      { id: 3, name: 'Casi siempre', quest: 'B.1.2' },
      { id: 2, name: 'Algunas veces', quest: 'B.1.2' },
      { id: 1, name: 'No sé', quest: 'B.1.2' },
      { id: 0, name: 'No se hace', quest: 'B.1.2' },
    ],
  },
  {
    id: 'B.1.3',
    idIndex: 32,
    text: 'En la institución educativa existe una política que orienta el procedimiento para identificar los recursos requeridos por todos los estudiantes y por algunos que presentan necesidades específicas.',
    options: [
      { id: 4, name: 'Siempre', quest: 'B.1.3' },
      { id: 3, name: 'Casi siempre', quest: 'B.1.3' },
      { id: 2, name: 'Algunas veces', quest: 'B.1.3' },
      { id: 1, name: 'No sé', quest: 'B.1.3' },
      { id: 0, name: 'No se hace', quest: 'B.1.3' },
    ],
  },
  {
    id: 'B.2.3',
    idIndex: 33,
    text: 'La institución educativa facilita a cada estudiante los recursos que necesita en la preparación para la vida y el trabajo.',
    options: [
      { id: 4, name: 'Siempre', quest: 'B.2.3' },
      { id: 3, name: 'Casi siempre', quest: 'B.2.3' },
      { id: 2, name: 'Algunas veces', quest: 'B.2.3' },
      { id: 1, name: 'No sé', quest: 'B.2.3' },
      { id: 0, name: 'No se hace', quest: 'B.2.3' },
    ],
  },
  {
    id: 'B.2.4',
    idIndex: 34,
    text: 'En la institución educativa los docentes ajustan su práctica pedagógica al ritmo y estilo de aprendizaje de cada uno de los estudiantes.',
    options: [
      { id: 4, name: 'Siempre', quest: 'B.2.4' },
      { id: 3, name: 'Casi siempre', quest: 'B.2.4' },
      { id: 2, name: 'Algunas veces', quest: 'B.2.4' },
      { id: 1, name: 'No sé', quest: 'B.2.4' },
      { id: 0, name: 'No se hace', quest: 'B.2.4' },
    ],
  },
  {
    id: 'B.3.1',
    idIndex: 35,
    text: 'En la institución educativa la relación entre docentes y estudiantes se manifiesta en una comunicación respetuosa y amable.',
    options: [
      { id: 4, name: 'Siempre', quest: 'B.3.1' },
      { id: 3, name: 'Casi siempre', quest: 'B.3.1' },
      { id: 2, name: 'Algunas veces', quest: 'B.3.1' },
      { id: 1, name: 'No sé', quest: 'B.3.1' },
      { id: 0, name: 'No se hace', quest: 'B.3.1' },
    ],
  },
  {
    id: 'B.3.2',
    idIndex: 36,
    text: 'En la institución educativa la planeación y desarrollo de las clases responden a los intereses y necesidades de cada uno de los estudiantes.',
    options: [
      { id: 4, name: 'Siempre', quest: 'B.3.2' },
      { id: 3, name: 'Casi siempre', quest: 'B.3.2' },
      { id: 2, name: 'Algunas veces', quest: 'B.3.2' },
      { id: 1, name: 'No sé', quest: 'B.3.2' },
      { id: 0, name: 'No se hace', quest: 'B.3.2' },
    ],
  },
  {
    id: 'B.3.3',
    idIndex: 37,
    text: 'En la institución educativa se involucra a los estudiantes en su propio aprendizaje permitiéndoles participar en la elección de temas, actividades de clase y opciones de evaluación.',
    options: [
      { id: 4, name: 'Siempre', quest: 'B.3.3' },
      { id: 3, name: 'Casi siempre', quest: 'B.3.3' },
      { id: 2, name: 'Algunas veces', quest: 'B.3.3' },
      { id: 1, name: 'No sé', quest: 'B.3.3' },
      { id: 0, name: 'No se hace', quest: 'B.3.3' },
    ],
  },
  {
    id: 'B.3.4',
    idIndex: 38,
    text: 'En la institución educativa las diferentes estrategias de evaluación son objeto de análisis continuo que permite al docente generar acciones correctivas cuando el estudiante, cualquiera que sea su condición, no está logrando el desempeño esperado.',
    options: [
      { id: 4, name: 'Siempre', quest: 'B.3.4' },
      { id: 3, name: 'Casi siempre', quest: 'B.3.4' },
      { id: 2, name: 'Algunas veces', quest: 'B.3.4' },
      { id: 1, name: 'No sé', quest: 'B.3.4' },
      { id: 0, name: 'No se hace', quest: 'B.3.4' },
    ],
  },
  {
    id: 'B.4.1',
    idIndex: 39,
    text: 'En la institución educativa se definen mecanismos de seguimiento a las prácticas pedagógicas inclusivas para conocer sus resultados y el impacto de éstos en el desempeño académico de los estudiantes.',
    options: [
      { id: 4, name: 'Siempre', quest: 'B.4.1' },
      { id: 3, name: 'Casi siempre', quest: 'B.4.1' },
      { id: 2, name: 'Algunas veces', quest: 'B.4.1' },
      { id: 1, name: 'No sé', quest: 'B.4.1' },
      { id: 0, name: 'No se hace', quest: 'B.4.1' },
    ],
  },
  {
    id: 'B.4.2',
    idIndex: 40,
    text: 'En la institución educativa se analizan los resultados de las pruebas externas (SABER, ICFES, ECAES) para evaluar el impacto de las acciones internas que permiten minimizar las barreras para el aprendizaje de la población en situación de vulnerabilidad.',
    options: [
      { id: 4, name: 'Siempre', quest: 'B.4.2' },
      { id: 3, name: 'Casi siempre', quest: 'B.4.2' },
      { id: 2, name: 'Algunas veces', quest: 'B.4.2' },
      { id: 1, name: 'No sé', quest: 'B.4.2' },
      { id: 0, name: 'No se hace', quest: 'B.4.2' },
    ],
  },
  {
    id: 'B.4.3',
    idIndex: 41,
    text: 'La institución educativa realiza acciones que disminuyen las barreras para el aprendizaje, la participación y la convivencia cuando afectan la permanencia de los estudiantes.',
    options: [
      { id: 4, name: 'Siempre', quest: 'B.4.3' },
      { id: 3, name: 'Casi siempre', quest: 'B.4.3' },
      { id: 2, name: 'Algunas veces', quest: 'B.4.3' },
      { id: 1, name: 'No sé', quest: 'B.4.3' },
      { id: 0, name: 'No se hace', quest: 'B.4.3' },
    ],
  },
  {
    id: 'B.4.4',
    idIndex: 42,
    text: 'En la institución educativa los docentes y el comité de evaluación y promoción analizan los casos de los estudiantes que requieren actividades de recuperación para determinar las acciones correctivas y preventivas pertinentes.',
    options: [
      { id: 4, name: 'Siempre', quest: 'B.4.4' },
      { id: 3, name: 'Casi siempre', quest: 'B.4.4' },
      { id: 2, name: 'Algunas veces', quest: 'B.4.4' },
      { id: 1, name: 'No sé', quest: 'B.4.4' },
      { id: 0, name: 'No se hace', quest: 'B.4.4' },
    ],
  },
  {
    id: 'B.4.5',
    idIndex: 43,
    text: 'En la institución educativa los servicios o profesionales de apoyo se coordinan para fortalecer las acciones inclusivas con la comunidad educativa.',
    options: [
      { id: 4, name: 'Siempre', quest: 'B.4.5' },
      { id: 3, name: 'Casi siempre', quest: 'B.4.5' },
      { id: 2, name: 'Algunas veces', quest: 'B.4.5' },
      { id: 1, name: 'No sé', quest: 'B.4.5' },
      { id: 0, name: 'No se hace', quest: 'B.4.5' },
    ],
  },
  {
    id: 'B.4.6',
    idIndex: 44,
    text: 'La institución educativa facilita a los egresados que presentaron situación de vulnerabilidad la transición a la educación superior o formación para el trabajo y el desarrollo humano.',
    options: [
      { id: 4, name: 'Siempre', quest: 'B.4.6' },
      { id: 3, name: 'Casi siempre', quest: 'B.4.6' },
      { id: 2, name: 'Algunas veces', quest: 'B.4.6' },
      { id: 1, name: 'No sé', quest: 'B.4.6' },
      { id: 0, name: 'No se hace', quest: 'B.4.6' },
    ],
  },
  {
    title: 'Sección C',
    id: 'C.1.1',
    idIndex: 45,
    text: 'La institución educativa presenta alternativas de ingreso a la población en situación de desplazamiento, desastre o abandono y que no tienen la documentación completa requerida para legalizar el proceso.',
    options: [
      { id: 4, name: 'Siempre', quest: 'C.1.1' },
      { id: 3, name: 'Casi siempre', quest: 'C.1.1' },
      { id: 2, name: 'Algunas veces', quest: 'C.1.1' },
      { id: 1, name: 'No sé', quest: 'C.1.1' },
      { id: 0, name: 'No se hace', quest: 'C.1.1' },
    ],
  },
  {
    id: 'C.1.2',
    idIndex: 46,
    text: 'La institución educativa tiene registros en su archivo académico que permita certificar las competencias a los estudiantes en el momento que los requiera.',
    options: [
      { id: 4, name: 'Siempre', quest: 'C.1.2' },
      { id: 3, name: 'Casi siempre', quest: 'C.1.2' },
      { id: 2, name: 'Algunas veces', quest: 'C.1.2' },
      { id: 1, name: 'No sé', quest: 'C.1.2' },
      { id: 0, name: 'No se hace', quest: 'C.1.2' },
    ],
  },
  {
    id: 'C.1.3',
    idIndex: 47,
    text: 'La institución educativa realiza procesos de registro sistemático de los logros de aquellos estudiantes que requieren flexibilización curricular.',
    options: [
      { id: 4, name: 'Siempre', quest: 'C.1.3' },
      { id: 3, name: 'Casi siempre', quest: 'C.1.3' },
      { id: 2, name: 'Algunas veces', quest: 'C.1.3' },
      { id: 1, name: 'No sé', quest: 'C.1.3' },
      { id: 0, name: 'No se hace', quest: 'C.1.3' },
    ],
  },
  {
    id: 'C.2.2',
    idIndex: 48,
    text: 'La institución educativa conoce y cumple con la normatividad del país sobre accesibilidad.',
    options: [
      { id: 4, name: 'Siempre', quest: 'C.2.2' },
      { id: 3, name: 'Casi siempre', quest: 'C.2.2' },
      { id: 2, name: 'Algunas veces', quest: 'C.2.2' },
      { id: 1, name: 'No sé', quest: 'C.2.2' },
      { id: 0, name: 'No se hace', quest: 'C.2.2' },
    ],
  },
  {
    id: 'C.2.3',
    idIndex: 49,
    text: 'La institución educativa tiene una política para asignar el uso de los espacios de manera equitativa para todos los estudiantes haciendo seguimiento a su cumplimiento.',
    options: [
      { id: 4, name: 'Siempre', quest: 'C.2.3' },
      { id: 3, name: 'Casi siempre', quest: 'C.2.3' },
      { id: 2, name: 'Algunas veces', quest: 'C.2.3' },
      { id: 1, name: 'No sé', quest: 'C.2.3' },
      { id: 0, name: 'No se hace', quest: 'C.2.3' },
    ],
  },
  {
    id: 'C.2.6',
    idIndex: 50,
    text: 'En la institución educativa la adquisición, dotación y mantenimiento de los recursos para el aprendizaje se realiza de manera equitativa teniendo en cuenta las necesidades grupales e individuales.',
    options: [
      { id: 4, name: 'Siempre', quest: 'C.2.6' },
      { id: 3, name: 'Casi siempre', quest: 'C.2.6' },
      { id: 2, name: 'Algunas veces', quest: 'C.2.6' },
      { id: 1, name: 'No sé', quest: 'C.2.6' },
      { id: 0, name: 'No se hace', quest: 'C.2.6' },
    ],
  },
  {
    id: 'C.2.7',
    idIndex: 51,
    text: 'La institución educativa tiene una política para prevenir los riesgos de accidentes de los estudiantes que presentan limitaciones físicas, enfermedades o barreras culturales.',
    options: [
      { id: 4, name: 'Siempre', quest: 'C.2.7' },
      { id: 3, name: 'Casi siempre', quest: 'C.2.7' },
      { id: 2, name: 'Algunas veces', quest: 'C.2.7' },
      { id: 1, name: 'No sé', quest: 'C.2.7' },
      { id: 0, name: 'No se hace', quest: 'C.2.7' },
    ],
  },
  {
    id: 'C.3.1',
    idIndex: 52,
    text: 'En la institución los servicios complementarios (transporte, alimentación, salud) que se ofrece, satisfacen las necesidades de los estudiantes que más lo requieren.',
    options: [
      { id: 4, name: 'Siempre', quest: 'C.3.1' },
      { id: 3, name: 'Casi siempre', quest: 'C.3.1' },
      { id: 2, name: 'Algunas veces', quest: 'C.3.1' },
      { id: 1, name: 'No sé', quest: 'C.3.1' },
      { id: 0, name: 'No se hace', quest: 'C.3.1' },
    ],
  },
  {
    id: 'C.4.1',
    idIndex: 53,
    text: 'En la institución educativa el personal que labora responde al perfil definido para atender las características y necesidades de su población.',
    options: [
      { id: 4, name: 'Siempre', quest: 'C.4.1' },
      { id: 3, name: 'Casi siempre', quest: 'C.4.1' },
      { id: 2, name: 'Algunas veces', quest: 'C.4.1' },
      { id: 1, name: 'No sé', quest: 'C.4.1' },
      { id: 0, name: 'No se hace', quest: 'C.4.1' },
    ],
  },
  {
    id: 'C.4.2',
    idIndex: 54,
    text: 'En la institución educativa el personal que labora responde al perfil definido para atender las características y necesidades de su población.',
    options: [
      { id: 4, name: 'Siempre', quest: 'C.4.2' },
      { id: 3, name: 'Casi siempre', quest: 'C.4.2' },
      { id: 2, name: 'Algunas veces', quest: 'C.4.2' },
      { id: 1, name: 'No sé', quest: 'C.4.2' },
      { id: 0, name: 'No se hace', quest: 'C.4.2' },
    ],
  },
  {
    id: 'C.4.3',
    idIndex: 55,
    text: 'En la institución educativa el programa de formación y capacitación para el personal de la institución incluye propuestas innovadoras que respondan a las necesidades y demandas específicas de la atención a la diversidad de los estudiantes.',
    options: [
      { id: 4, name: 'Siempre', quest: 'C.4.3' },
      { id: 3, name: 'Casi siempre', quest: 'C.4.3' },
      { id: 2, name: 'Algunas veces', quest: 'C.4.3' },
      { id: 1, name: 'No sé', quest: 'C.4.3' },
      { id: 0, name: 'No se hace', quest: 'C.4.3' },
    ],
  },
  {
    id: 'C.4.4',
    idIndex: 56,
    text: 'En la institución educativa la asignación académica se realiza de manera equitativa, en coherencia con los perfiles y fortalezas de los docentes y las demandas de atención a la diversidad de los estudiantes.',
    options: [
      { id: 4, name: 'Siempre', quest: 'C.4.4' },
      { id: 3, name: 'Casi siempre', quest: 'C.4.4' },
      { id: 2, name: 'Algunas veces', quest: 'C.4.4' },
      { id: 1, name: 'No sé', quest: 'C.4.4' },
      { id: 0, name: 'No se hace', quest: 'C.4.4' },
    ],
  },
  {
    id: 'C.4.5',
    idIndex: 57,
    text: 'En la institución los integrantes de la comunidad educativa se identifican y comparten la filosofía, principios, valores y objetivos de la educación inclusiva.',
    options: [
      { id: 4, name: 'Siempre', quest: 'C.4.5' },
      { id: 3, name: 'Casi siempre', quest: 'C.4.5' },
      { id: 2, name: 'Algunas veces', quest: 'C.4.5' },
      { id: 1, name: 'No sé', quest: 'C.4.5' },
      { id: 0, name: 'No se hace', quest: 'C.4.5' },
    ],
  },
  {
    id: 'C.4.6',
    idIndex: 58,
    text: 'En la institución educativa la evaluación de desempeño de los directivos, administrativos y docentes incluye las innovaciones para fortalecer la atención a la diversidad.',
    options: [
      { id: 4, name: 'Siempre', quest: 'C.4.6' },
      { id: 3, name: 'Casi siempre', quest: 'C.4.6' },
      { id: 2, name: 'Algunas veces', quest: 'C.4.6' },
      { id: 1, name: 'No sé', quest: 'C.4.6' },
      { id: 0, name: 'No se hace', quest: 'C.4.6' },
    ],
  },
  {
    id: 'C.4.7',
    idIndex: 59,
    text: 'En la institución educativa se reconocen y estimulan los valores y las habilidades sociales, artísticas, deportivas, de aprendizaje de todos los integrantes de la comunidad educativa.',
    options: [
      { id: 4, name: 'Siempre', quest: 'C.4.7' },
      { id: 3, name: 'Casi siempre', quest: 'C.4.7' },
      { id: 2, name: 'Algunas veces', quest: 'C.4.7' },
      { id: 1, name: 'No sé', quest: 'C.4.7' },
      { id: 0, name: 'No se hace', quest: 'C.4.7' },
    ],
  },
  {
    id: 'C.4.8',
    idIndex: 60,
    text: 'La institución educativa tiene una política que promueve la investigación en temas relacionados con atención a la diversidad.',
    options: [
      { id: 4, name: 'Siempre', quest: 'C.4.8' },
      { id: 3, name: 'Casi siempre', quest: 'C.4.8' },
      { id: 2, name: 'Algunas veces', quest: 'C.4.8' },
      { id: 1, name: 'No sé', quest: 'C.4.8' },
      { id: 0, name: 'No se hace', quest: 'C.4.8' },
    ],
  },
  {
    id: 'C.4.9',
    idIndex: 61,
    text: 'La institución educativa desarrolla estrategias de formación en habilidades de trabajo colaborativo y resolución de conflictos para favorecer la convivencia y el clima laboral.',
    options: [
      { id: 4, name: 'Siempre', quest: 'C.4.9' },
      { id: 3, name: 'Casi siempre', quest: 'C.4.9' },
      { id: 2, name: 'Algunas veces', quest: 'C.4.9' },
      { id: 1, name: 'No sé', quest: 'C.4.9' },
      { id: 0, name: 'No se hace', quest: 'C.4.9' },
    ],
  },
  {
    id: 'C.4.10',
    idIndex: 62,
    text: 'En la institución educativa los servicios de bienestar de la institución se prestan teniendo en cuenta las necesidades de todo su personal.',
    options: [
      { id: 4, name: 'Siempre', quest: 'C.4.10' },
      { id: 3, name: 'Casi siempre', quest: 'C.4.10' },
      { id: 2, name: 'Algunas veces', quest: 'C.4.10' },
      { id: 1, name: 'No sé', quest: 'C.4.10' },
      { id: 0, name: 'No se hace', quest: 'C.4.10' },
    ],
  },
  {
    id: 'C.5.2',
    idIndex: 63,
    text: 'La institución educativa tiene una política de destinación de recursos financieros para atender a la población en situación de vulnerabilidad.',
    options: [
      { id: 4, name: 'Siempre', quest: 'C.5.2' },
      { id: 3, name: 'Casi siempre', quest: 'C.5.2' },
      { id: 2, name: 'Algunas veces', quest: 'C.5.2' },
      { id: 1, name: 'No sé', quest: 'C.5.2' },
      { id: 0, name: 'No se hace', quest: 'C.5.2' },
    ],
  },
  {
    title: 'Sección D',
    id: 'D.1.1',
    idIndex: 64,
    text: 'La institución educativa durante todo el proceso de formación, ayuda a cada uno de los estudiantes a conocerse a sí mismo, para elaborar y desarrollar su proyecto de vida.',
    options: [
      { id: 4, name: 'Siempre', quest: 'D.1.1' },
      { id: 3, name: 'Casi siempre', quest: 'D.1.1' },
      { id: 2, name: 'Algunas veces', quest: 'D.1.1' },
      { id: 1, name: 'No sé', quest: 'D.1.1' },
      { id: 0, name: 'No se hace', quest: 'D.1.1' },
    ],
  },
  {
    id: 'D.2.1',
    idIndex: 65,
    text: 'La institución educativa en su escuela de padres desarrolla temas y actividades relacionadas con valores inclusivos como: equidad, igualdad de oportunidades, reconocimiento, respeto por la diferencia, cooperación y solidaridad.',
    options: [
      { id: 4, name: 'Siempre', quest: 'D.2.1' },
      { id: 3, name: 'Casi siempre', quest: 'D.2.1' },
      { id: 2, name: 'Algunas veces', quest: 'D.2.1' },
      { id: 1, name: 'No sé', quest: 'D.2.1' },
      { id: 0, name: 'No se hace', quest: 'D.2.1' },
    ],
  },
  {
    id: 'D.2.2',
    idIndex: 66,
    text: 'La institución educativa realiza actividades culturales, recreativas, deportivas y académicas con las personas del sector para promover la inclusión en su comunidad.',
    options: [
      { id: 4, name: 'Siempre', quest: 'D.2.2' },
      { id: 3, name: 'Casi siempre', quest: 'D.2.2' },
      { id: 2, name: 'Algunas veces', quest: 'D.2.2' },
      { id: 1, name: 'No sé', quest: 'D.2.2' },
      { id: 0, name: 'No se hace', quest: 'D.2.2' },
    ],
  },
  {
    id: 'D.2.3',
    idIndex: 67,
    text: 'En la institución educativa el programa de servicio social desarrolla propuestas para que algunos estudiantes acompañen y ayuden a otros que lo necesiten.',
    options: [
      { id: 4, name: 'Siempre', quest: 'D.2.3' },
      { id: 3, name: 'Casi siempre', quest: 'D.2.3' },
      { id: 2, name: 'Algunas veces', quest: 'D.2.3' },
      { id: 1, name: 'No sé', quest: 'D.2.3' },
      { id: 0, name: 'No se hace', quest: 'D.2.3' },
    ],
  },
  {
    id: 'D.3.1',
    idIndex: 68,
    text: 'En la institución educativa los estudiantes en situación de vulnerabilidad tienen la oportunidad de representar la institución y participar en actividades culturales, recreativas deportivas y académicas que se realizan en la institución.',
    options: [
      { id: 4, name: 'Siempre', quest: 'D.3.1' },
      { id: 3, name: 'Casi siempre', quest: 'D.3.1' },
      { id: 2, name: 'Algunas veces', quest: 'D.3.1' },
      { id: 1, name: 'No sé', quest: 'D.3.1' },
      { id: 0, name: 'No se hace', quest: 'D.3.1' },
    ],
  },
  {
    id: 'D.3.2',
    idIndex: 69,
    text: 'En la institución educativa la Asamblea y Consejo de padres cuentan con la participación de familias de estudiantes en situación de vulnerabilidad, que aportan a la evaluación y definición de acciones inclusivas.',
    options: [
      { id: 4, name: 'Siempre', quest: 'D.3.2' },
      { id: 3, name: 'Casi siempre', quest: 'D.3.2' },
      { id: 2, name: 'Algunas veces', quest: 'D.3.2' },
      { id: 1, name: 'No sé', quest: 'D.3.2' },
      { id: 0, name: 'No se hace', quest: 'D.3.2' },
    ],
  },
  {
    id: 'D.3.3',
    idIndex: 70,
    text: 'En la institución educativa se desarrollan propuestas de programas de apoyo familia a familia para fortalecer las habilidades colaborativas entre ellas.',
    options: [
      { id: 4, name: 'Siempre', quest: 'D.3.3' },
      { id: 3, name: 'Casi siempre', quest: 'D.3.3' },
      { id: 2, name: 'Algunas veces', quest: 'D.3.3' },
      { id: 1, name: 'No sé', quest: 'D.3.3' },
      { id: 0, name: 'No se hace', quest: 'D.3.3' },
    ],
  },
  {
    id: 'D.4.1',
    idIndex: 71,
    text: 'En la institución educativa se realizan acciones comprensibles para cada uno de los estudiantes con el fin de prevenir accidentes y enfermedades.',
    options: [
      { id: 4, name: 'Siempre', quest: 'D.4.1' },
      { id: 3, name: 'Casi siempre', quest: 'D.4.1' },
      { id: 2, name: 'Algunas veces', quest: 'D.4.1' },
      { id: 1, name: 'No sé', quest: 'D.4.1' },
      { id: 0, name: 'No se hace', quest: 'D.4.1' },
    ],
  },
  {
    id: 'D.4.2',
    idIndex: 72,
    text: 'En la institución educativa se realizan acciones comprensibles para prevenir la drogadicción, el alcoholismo, las enfermedades de transmisión sexual, el abuso, el maltrato físico y verbal, entre otras, que pueden afectar a los estudiantes.',
    options: [
      { id: 4, name: 'Siempre', quest: 'D.4.2' },
      { id: 3, name: 'Casi siempre', quest: 'D.4.2' },
      { id: 2, name: 'Algunas veces', quest: 'D.4.2' },
      { id: 1, name: 'No sé', quest: 'D.4.2' },
      { id: 0, name: 'No se hace', quest: 'D.4.2' },
    ],
  },
  {
    id: 'D.4.3',
    idIndex: 73,
    text: 'En la institución educativa se realizan actividades de entrenamiento para que todas las personas, incluso las que presentan limitaciones, aprendan qué hacer en caso de desastres como: incendios, terremotos, inundación, entre otros.',
    options: [
      { id: 4, name: 'Siempre', quest: 'D.4.3' },
      { id: 3, name: 'Casi siempre', quest: 'D.4.3' },
      { id: 2, name: 'Algunas veces', quest: 'D.4.3' },
      { id: 1, name: 'No sé', quest: 'D.4.3' },
      { id: 0, name: 'No se hace', quest: 'D.4.3' },
    ],
  },
];

export const listQuestionForm2 = [
  {
    title: 'Sección A',
    id: 'A.1.1',
    idIndex: 0,
    text: 'La institución educativa admite a toda la población del sector sin discriminación de raza, cultura, género, ideología, credo, preferencia sexual, condición socioeconómica o situación de vulnerabilidad, como: desplazamiento, violencia y analfabetismo, entre otros.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.1.1' },
      { id: 3, name: 'Casi siempre', quest: 'A.1.1' },
      { id: 2, name: 'Algunas veces', quest: 'A.1.1' },
      { id: 1, name: 'No sé', quest: 'A.1.1' },
      { id: 0, name: 'No se hace', quest: 'A.1.1' },
    ],
  },
  {
    id: 'A.1.2',
    idIndex: 1,
    text: 'Toda la población que ingresa a la institución educativa recibe una atención que garantiza el aprendizaje, la participación, la convivencia  y el avance de un grado a otro preparándola para la vida y el trabajo.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.1.2' },
      { id: 3, name: 'Casi siempre', quest: 'A.1.2' },
      { id: 2, name: 'Algunas veces', quest: 'A.1.2' },
      { id: 1, name: 'No sé', quest: 'A.1.2' },
      { id: 0, name: 'No se hace', quest: 'A.1.2' },
    ],
  },
  {
    id: 'A.1.3',
    idIndex: 2,
    text: 'La institución  invita a su comunidad educativa a conocer y desarrollar actividades centradas en el respeto a la diferencia, que faciliten el aprendizaje, la participación y la convivencia de toda la población.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.1.3' },
      { id: 3, name: 'Casi siempre', quest: 'A.1.3' },
      { id: 2, name: 'Algunas veces', quest: 'A.1.3' },
      { id: 1, name: 'No sé', quest: 'A.1.3' },
      { id: 0, name: 'No se hace', quest: 'A.1.3' },
    ],
  },
  {
    id: 'A.2.1',
    idIndex: 3,
    text: 'La institución tiene como política involucrar a su comunidad educativa en la evaluación y el diseño de propuestas para cualificar el aprendizaje, la participación, la convivencia y el respeto por la diferencia.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.2.1' },
      { id: 3, name: 'Casi siempre', quest: 'A.2.1' },
      { id: 2, name: 'Algunas veces', quest: 'A.2.1' },
      { id: 1, name: 'No sé', quest: 'A.2.1' },
      { id: 0, name: 'No se hace', quest: 'A.2.1' },
    ],
  },
  {
    id: 'A.2.4',
    idIndex: 4,
    text: 'La institución educativa da a conocer los resultados del Índice de Inclusión a las familias y los estudiantes.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.2.4' },
      { id: 3, name: 'Casi siempre', quest: 'A.2.4' },
      { id: 2, name: 'Algunas veces', quest: 'A.2.4' },
      { id: 1, name: 'No sé', quest: 'A.2.4' },
      { id: 0, name: 'No se hace', quest: 'A.2.4' },
    ],
  },
  {
    id: 'A.3.1',
    idIndex: 5,
    text: 'En la institución el Consejo Directivo escribe y vigila  las formas en que debe hacerse la atención  educativa para todos sus estudiantes.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.3.1' },
      { id: 3, name: 'Casi siempre', quest: 'A.3.1' },
      { id: 2, name: 'Algunas veces', quest: 'A.3.1' },
      { id: 1, name: 'No sé', quest: 'A.3.1' },
      { id: 0, name: 'No se hace', quest: 'A.3.1' },
    ],
  },
  {
    id: 'A.3.2',
    idIndex: 6,
    text: 'En la institución educativa el Consejo Académico explica diferentes formas de enseñanza y de comunicarse con palabras, gestos, señas y dibujos que permitan a todos los estudiantes aprender.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.3.2' },
      { id: 3, name: 'Casi siempre', quest: 'A.3.2' },
      { id: 2, name: 'Algunas veces', quest: 'A.3.2' },
      { id: 1, name: 'No sé', quest: 'A.3.2' },
      { id: 0, name: 'No se hace', quest: 'A.3.2' },
    ],
  },
  {
    id: 'A.3.3',
    idIndex: 7,
    text: 'En la institución educativa el Comité de Evaluación y Promoción explica diferentes formas de evaluar: de manera escrita, oral, gestual y con dibujos; y tiene en cuenta la edad, los logros,  la motivación y las posibilidades de cada estudiante.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.3.3' },
      { id: 3, name: 'Casi siempre', quest: 'A.3.3' },
      { id: 2, name: 'Algunas veces', quest: 'A.3.3' },
      { id: 1, name: 'No sé', quest: 'A.3.3' },
      { id: 0, name: 'No se hace', quest: 'A.3.3' },
    ],
  },
  {
    id: 'A.3.4',
    idIndex: 8,
    text: 'En la institución educativa el comité de convivencia realiza actividades que permiten disminuir las expulsiones por  indisciplina.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.3.4' },
      { id: 3, name: 'Casi siempre', quest: 'A.3.4' },
      { id: 2, name: 'Algunas veces', quest: 'A.3.4' },
      { id: 1, name: 'No sé', quest: 'A.3.4' },
      { id: 0, name: 'No se hace', quest: 'A.3.4' },
    ],
  },
  {
    id: 'A.3.5',
    idIndex: 9,
    text: 'En la institución educativa se realiza la elección del Consejo Estudiantil con la participación de todos los estudiantes sin discriminación alguna. ',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.3.5' },
      { id: 3, name: 'Casi siempre', quest: 'A.3.5' },
      { id: 2, name: 'Algunas veces', quest: 'A.3.5' },
      { id: 1, name: 'No sé', quest: 'A.3.5' },
      { id: 0, name: 'No se hace', quest: 'A.3.5' },
    ],
  },
  {
    id: 'A.3.6',
    idIndex: 10,
    text: 'En la institución educativa se realiza la elección del Personero con la participación de todos los estudiantes sin discriminación alguna.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.3.6' },
      { id: 3, name: 'Casi siempre', quest: 'A.3.6' },
      { id: 2, name: 'Algunas veces', quest: 'A.3.6' },
      { id: 1, name: 'No sé', quest: 'A.3.6' },
      { id: 0, name: 'No se hace', quest: 'A.3.6' },
    ],
  },
  {
    id: 'A.4.1',
    idIndex: 11,
    text: 'La institución educativa emplea diferentes medios para informar, actualizar y motivar a los integrantes de su comunidad utilizando: murales, boletines, carteleras, afiches y reuniones comprensibles para todos.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.4.1' },
      { id: 3, name: 'Casi siempre', quest: 'A.4.1' },
      { id: 2, name: 'Algunas veces', quest: 'A.4.1' },
      { id: 1, name: 'No sé', quest: 'A.4.1' },
      { id: 0, name: 'No se hace', quest: 'A.4.1' },
    ],
  },
  {
    id: 'A.4.2',
    idIndex: 12,
    text: 'En la institución los integrantes de la comunidad educativa colaboran entre si para facilitar el aprendizaje, la participación y la convivencia de todos.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.4.2' },
      { id: 3, name: 'Casi siempre', quest: 'A.4.2' },
      { id: 2, name: 'Algunas veces', quest: 'A.4.2' },
      { id: 1, name: 'No sé', quest: 'A.4.2' },
      { id: 0, name: 'No se hace', quest: 'A.4.2' },
    ],
  },
  {
    id: 'A.4.3',
    idIndex: 13,
    text: 'En la institución educativa se reconoce y estimula  a los estudiantes que apoyan a sus compañeros en el aprendizaje, la participación y la convivencia.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.4.3' },
      { id: 3, name: 'Casi siempre', quest: 'A.4.3' },
      { id: 2, name: 'Algunas veces', quest: 'A.4.3' },
      { id: 1, name: 'No sé', quest: 'A.4.3' },
      { id: 0, name: 'No se hace', quest: 'A.4.3' },
    ],
  },
  {
    id: 'A.4.4',
    idIndex: 14,
    text: 'La institución educativa da a conocer experiencias importantes que sirvan para mejorar el aprendizaje, la participación y la convivencia de todos.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.4.4' },
      { id: 3, name: 'Casi siempre', quest: 'A.4.4' },
      { id: 2, name: 'Algunas veces', quest: 'A.4.4' },
      { id: 1, name: 'No sé', quest: 'A.4.4' },
      { id: 0, name: 'No se hace', quest: 'A.4.4' },
    ],
  },
  {
    id: 'A.5.1',
    idIndex: 15,
    text: 'En la institución las familias y estudiantes, se sienten orgullosos de pertenecer a una comunidad educativa donde se promueve el respeto y valoración por la diversidad.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.5.1' },
      { id: 3, name: 'Casi siempre', quest: 'A.5.1' },
      { id: 2, name: 'Algunas veces', quest: 'A.5.1' },
      { id: 1, name: 'No sé', quest: 'A.5.1' },
      { id: 0, name: 'No se hace', quest: 'A.5.1' },
    ],
  },
  {
    id: 'A.5.2',
    idIndex: 16,
    text: 'La institución educativa realiza acciones para que todas las personas puedan desplazarse sin dificultad por sus instalaciones.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.5.2' },
      { id: 3, name: 'Casi siempre', quest: 'A.5.2' },
      { id: 2, name: 'Algunas veces', quest: 'A.5.2' },
      { id: 1, name: 'No sé', quest: 'A.5.2' },
      { id: 0, name: 'No se hace', quest: 'A.5.2' },
    ],
  },
  {
    id: 'A.5.3',
    idIndex: 17,
    text: 'La institución educativa explica a estudiantes y  familias sus características, funcionamiento y normas de convivencia para que todos se sientan bienvenidos.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.5.3' },
      { id: 3, name: 'Casi siempre', quest: 'A.5.3' },
      { id: 2, name: 'Algunas veces', quest: 'A.5.3' },
      { id: 1, name: 'No sé', quest: 'A.5.3' },
      { id: 0, name: 'No se hace', quest: 'A.5.3' },
    ],
  },
  {
    id: 'A.5.4',
    idIndex: 18,
    text: 'La institución educativa realiza acciones para que los estudiantes se motiven por aprender teniendo en cuenta sus habilidades e intereses.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.5.4' },
      { id: 3, name: 'Casi siempre', quest: 'A.5.4' },
      { id: 2, name: 'Algunas veces', quest: 'A.5.4' },
      { id: 1, name: 'No sé', quest: 'A.5.4' },
      { id: 0, name: 'No se hace', quest: 'A.5.4' },
    ],
  },
  {
    id: 'A.5.5',
    idIndex: 19,
    text: 'En la institución educativa el manual de convivencia  orienta y promueve el respeto y valoración de la diversidad que se presenta en su comunidad.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.5.5' },
      { id: 3, name: 'Casi siempre', quest: 'A.5.5' },
      { id: 2, name: 'Algunas veces', quest: 'A.5.5' },
      { id: 1, name: 'No sé', quest: 'A.5.5' },
      { id: 0, name: 'No se hace', quest: 'A.5.5' },
    ],
  },
  {
    id: 'A.5.6',
    idIndex: 20,
    text: 'En la institución educativa todos los estudiantes tienen la oportunidad de participar en actividades complementarias y  extracurriculares que posibilitan el desarrollo de habilidades e intereses.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.5.6' },
      { id: 3, name: 'Casi siempre', quest: 'A.5.6' },
      { id: 2, name: 'Algunas veces', quest: 'A.5.6' },
      { id: 1, name: 'No sé', quest: 'A.5.6' },
      { id: 0, name: 'No se hace', quest: 'A.5.6' },
    ],
  },
  {
    id: 'A.5.7',
    idIndex: 21,
    text: 'En la institución educativa los servicios de bienestar se ofrecen a  los estudiantes que más lo requieren.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.5.7' },
      { id: 3, name: 'Casi siempre', quest: 'A.5.7' },
      { id: 2, name: 'Algunas veces', quest: 'A.5.7' },
      { id: 1, name: 'No sé', quest: 'A.5.7' },
      { id: 0, name: 'No se hace', quest: 'A.5.7' },
    ],
  },
  {
    id: 'A.5.8',
    idIndex: 22,
    text: 'En la institución educativa cuando los estudiantes tienen problemas se les escucha,  se les ayuda a solucionarlos y se les enseña  a mejorar su comportamiento.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.5.8' },
      { id: 3, name: 'Casi siempre', quest: 'A.5.8' },
      { id: 2, name: 'Algunas veces', quest: 'A.5.8' },
      { id: 1, name: 'No sé', quest: 'A.5.8' },
      { id: 0, name: 'No se hace', quest: 'A.5.8' },
    ],
  },
  {
    id: 'A.6.1',
    idIndex: 23,
    text: 'La institución educativa realiza actividades para conocer las condiciones de la familia y ayudarla a resolver sus problemas.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.6.1' },
      { id: 3, name: 'Casi siempre', quest: 'A.6.1' },
      { id: 2, name: 'Algunas veces', quest: 'A.6.1' },
      { id: 1, name: 'No sé', quest: 'A.6.1' },
      { id: 0, name: 'No se hace', quest: 'A.6.1' },
    ],
  },
  {
    id: 'A.6.3',
    idIndex: 24,
    text: 'La institución educativa aprovecha y da a conocer los recursos existentes en la comunidad para facilitar su desarrollo y la participación de todos los estudiantes sin discriminación alguna.',
    options: [
      { id: 4, name: 'Siempre', quest: 'A.6.3' },
      { id: 3, name: 'Casi siempre', quest: 'A.6.3' },
      { id: 2, name: 'Algunas veces', quest: 'A.6.3' },
      { id: 1, name: 'No sé', quest: 'A.6.3' },
      { id: 0, name: 'No se hace', quest: 'A.6.3' },
    ],
  },
  {
    title: 'Sección B',
    id: 'B.1.4',
    idIndex: 25,
    text: 'En la institución educativa la distribución de tiempos en la jornada se revisa y ajusta para atender a necesidades de cada uno de los estudiantes, como: adaptación, alimentación, aprendizaje, entre otras.',
    options: [
      { id: 4, name: 'Siempre', quest: 'B.1.4' },
      { id: 3, name: 'Casi siempre', quest: 'B.1.4' },
      { id: 2, name: 'Algunas veces', quest: 'B.1.4' },
      { id: 1, name: 'No sé', quest: 'B.1.4' },
      { id: 0, name: 'No se hace', quest: 'B.1.4' },
    ],
  },
  {
    id: 'B.2.1',
    idIndex: 26,
    text: 'En la institución educativa los docentes implementan diferentes opciones de didácticas flexibles para facilitar el aprendizaje  de cada uno de los estudiantes de acuerdo con sus características y necesidades.',
    options: [
      { id: 4, name: 'Siempre', quest: 'B.2.1' },
      { id: 3, name: 'Casi siempre', quest: 'B.2.1' },
      { id: 2, name: 'Algunas veces', quest: 'B.2.1' },
      { id: 1, name: 'No sé', quest: 'B.2.1' },
      { id: 0, name: 'No se hace', quest: 'B.2.1' },
    ],
  },
  {
    id: 'B.2.2',
    idIndex: 27,
    text: 'En la institución educativa los estudiantes pueden elegir tareas de su agrado que les ayuden a reforzar sus habilidades y conocimientos.',
    options: [
      { id: 4, name: 'Siempre', quest: 'B.2.2' },
      { id: 3, name: 'Casi siempre', quest: 'B.2.2' },
      { id: 2, name: 'Algunas veces', quest: 'B.2.2' },
      { id: 1, name: 'No sé', quest: 'B.2.2' },
      { id: 0, name: 'No se hace', quest: 'B.2.2' },
    ],
  },
  {
    id: 'B.2.3',
    idIndex: 28,
    text: 'La institución educativa facilita a cada estudiante los recursos que necesita en la preparación para la vida y el trabajo.',
    options: [
      { id: 4, name: 'Siempre', quest: 'B.2.3' },
      { id: 3, name: 'Casi siempre', quest: 'B.2.3' },
      { id: 2, name: 'Algunas veces', quest: 'B.2.3' },
      { id: 1, name: 'No sé', quest: 'B.2.3' },
      { id: 0, name: 'No se hace', quest: 'B.2.3' },
    ],
  },
  {
    id: 'B.2.4',
    idIndex: 29,
    text: 'En la institución educativa los  docentes realizan actividades para los estudiantes que aprenden rápido y para quienes necesitan más tiempo.',
    options: [
      { id: 4, name: 'Siempre', quest: 'B.2.4' },
      { id: 3, name: 'Casi siempre', quest: 'B.2.4' },
      { id: 2, name: 'Algunas veces', quest: 'B.2.4' },
      { id: 1, name: 'No sé', quest: 'B.2.4' },
      { id: 0, name: 'No se hace', quest: 'B.2.4' },
    ],
  },
  {
    id: 'B.3.1',
    idIndex: 30,
    text: 'En la institución educativa la relación entre docentes y estudiantes se manifiesta en una comunicación respetuosa y amable.',
    options: [
      { id: 4, name: 'Siempre', quest: 'B.3.1' },
      { id: 3, name: 'Casi siempre', quest: 'B.3.1' },
      { id: 2, name: 'Algunas veces', quest: 'B.3.1' },
      { id: 1, name: 'No sé', quest: 'B.3.1' },
      { id: 0, name: 'No se hace', quest: 'B.3.1' },
    ],
  },
  {
    id: 'B.3.2',
    idIndex: 31,
    text: 'En la institución educativa las actividades realizadas en clase las entienden y disfrutan todos los estudiantes.',
    options: [
      { id: 4, name: 'Siempre', quest: 'B.3.2' },
      { id: 3, name: 'Casi siempre', quest: 'B.3.2' },
      { id: 2, name: 'Algunas veces', quest: 'B.3.2' },
      { id: 1, name: 'No sé', quest: 'B.3.2' },
      { id: 0, name: 'No se hace', quest: 'B.3.2' },
    ],
  },
  {
    id: 'B.3.3',
    idIndex: 32,
    text: 'En la institución educativa los estudiantes participan en la elección de temas, actividades de clase y formas de evaluación.',
    options: [
      { id: 4, name: 'Siempre', quest: 'B.3.3' },
      { id: 3, name: 'Casi siempre', quest: 'B.3.3' },
      { id: 2, name: 'Algunas veces', quest: 'B.3.3' },
      { id: 1, name: 'No sé', quest: 'B.3.3' },
      { id: 0, name: 'No se hace', quest: 'B.3.3' },
    ],
  },
  {
    id: 'B.3.4',
    idIndex: 33,
    text: 'En la institución educativa los docentes utilizan diferentes maneras de evaluar, como: juegos, dibujos, exámenes orales y escritos para que todos los estudiantes demuestren lo que han aprendido.',
    options: [
      { id: 4, name: 'Siempre', quest: 'B.3.4' },
      { id: 3, name: 'Casi siempre', quest: 'B.3.4' },
      { id: 2, name: 'Algunas veces', quest: 'B.3.4' },
      { id: 1, name: 'No sé', quest: 'B.3.4' },
      { id: 0, name: 'No se hace', quest: 'B.3.4' },
    ],
  },
  {
    id: 'B.4.1',
    idIndex: 34,
    text: 'La institución educativa hace reuniones con familias y estudiantes para compartir los cambios realizados en las clases, las evaluaciones y las tareas.',
    options: [
      { id: 4, name: 'Siempre', quest: 'B.4.1' },
      { id: 3, name: 'Casi siempre', quest: 'B.4.1' },
      { id: 2, name: 'Algunas veces', quest: 'B.4.1' },
      { id: 1, name: 'No sé', quest: 'B.4.1' },
      { id: 0, name: 'No se hace', quest: 'B.4.1' },
    ],
  },
  {
    id: 'B.4.2',
    idIndex: 35,
    text: 'La institución educativa comparte con familias y estudiantes los resultados de las pruebas (SABER, ICFES, ECAES) para tomar decisiones que mejoren la enseñanza y el aprendizaje.',
    options: [
      { id: 4, name: 'Siempre', quest: 'B.4.2' },
      { id: 3, name: 'Casi siempre', quest: 'B.4.2' },
      { id: 2, name: 'Algunas veces', quest: 'B.4.2' },
      { id: 1, name: 'No sé', quest: 'B.4.2' },
      { id: 0, name: 'No se hace', quest: 'B.4.2' },
    ],
  },
  {
    id: 'B.4.3',
    idIndex: 36,
    text: 'En la institución educativa se realizan acciones para garantizar la permanencia de todos los estudiantes.',
    options: [
      { id: 4, name: 'Siempre', quest: 'B.4.3' },
      { id: 3, name: 'Casi siempre', quest: 'B.4.3' },
      { id: 2, name: 'Algunas veces', quest: 'B.4.3' },
      { id: 1, name: 'No sé', quest: 'B.4.3' },
      { id: 0, name: 'No se hace', quest: 'B.4.3' },
    ],
  },
  {
    id: 'B.4.4',
    idIndex: 37,
    text: 'En la institución educativa los docentes acompañan a los estudiantes en la realización de las actividades de recuperación brindándoles los apoyos que requieren.',
    options: [
      { id: 4, name: 'Siempre', quest: 'B.4.4' },
      { id: 3, name: 'Casi siempre', quest: 'B.4.4' },
      { id: 2, name: 'Algunas veces', quest: 'B.4.4' },
      { id: 1, name: 'No sé', quest: 'B.4.4' },
      { id: 0, name: 'No se hace', quest: 'B.4.4' },
    ],
  },
  {
    id: 'B.4.5',
    idIndex: 38,
    text: 'En la institución educativa los estudiantes reciben las ayudas necesarias para aprender y socializarse.',
    options: [
      { id: 4, name: 'Siempre', quest: 'B.4.5' },
      { id: 3, name: 'Casi siempre', quest: 'B.4.5' },
      { id: 2, name: 'Algunas veces', quest: 'B.4.5' },
      { id: 1, name: 'No sé', quest: 'B.4.5' },
      { id: 0, name: 'No se hace', quest: 'B.4.5' },
    ],
  },
  {
    title: 'Sección D',
    id: 'D.1.1',
    idIndex: 39,
    text: 'La institución educativa durante todo su proceso de formación ayuda a cada uno de los estudiantes a conocerse a si mismo para elaborar y desarrollar  su proyecto de vida.',
    options: [
      { id: 4, name: 'Siempre', quest: 'D.1.1' },
      { id: 3, name: 'Casi siempre', quest: 'D.1.1' },
      { id: 2, name: 'Algunas veces', quest: 'D.1.1' },
      { id: 1, name: 'No sé', quest: 'D.1.1' },
      { id: 0, name: 'No se hace', quest: 'D.1.1' },
    ],
  },
  {
    id: 'D.2.1',
    idIndex: 40,
    text: 'La institución educativa en su escuela de padres, desarrolla temas y actividades relacionados con valores inclusivos como: equidad, igualdad de oportunidades, reconocimiento y respeto a la diferencia, la cooperación y la solidaridad.',
    options: [
      { id: 4, name: 'Siempre', quest: 'D.2.1' },
      { id: 3, name: 'Casi siempre', quest: 'D.2.1' },
      { id: 2, name: 'Algunas veces', quest: 'D.2.1' },
      { id: 1, name: 'No sé', quest: 'D.2.1' },
      { id: 0, name: 'No se hace', quest: 'D.2.1' },
    ],
  },
  {
    id: 'D.2.2',
    idIndex: 41,
    text: 'La institución educativa realiza actividades culturales, recreativas, deportivas y académicas con las personas del sector para promover la inclusión en su comunidad.',
    options: [
      { id: 4, name: 'Siempre', quest: 'D.2.2' },
      { id: 3, name: 'Casi siempre', quest: 'D.2.2' },
      { id: 2, name: 'Algunas veces', quest: 'D.2.2' },
      { id: 1, name: 'No sé', quest: 'D.2.2' },
      { id: 0, name: 'No se hace', quest: 'D.2.2' },
    ],
  },
  {
    id: 'D.2.3',
    idIndex: 42,
    text: 'En la institución educativa el programa de servicio social desarrolla propuestas para que algunos estudiantes acompañen y ayuden a otros que lo necesiten.  ',
    options: [
      { id: 4, name: 'Siempre', quest: 'D.2.3' },
      { id: 3, name: 'Casi siempre', quest: 'D.2.3' },
      { id: 2, name: 'Algunas veces', quest: 'D.2.3' },
      { id: 1, name: 'No sé', quest: 'D.2.3' },
      { id: 0, name: 'No se hace', quest: 'D.2.3' },
    ],
  },
  {
    id: 'D.3.1',
    idIndex: 43,
    text: 'En la institución educativa los estudiantes en situación de vulnerabilidad tienen la oportunidad de representar a la institución y participar en actividades culturales, recreativas, deportivas y académicas.',
    options: [
      { id: 4, name: 'Siempre', quest: 'D.3.1' },
      { id: 3, name: 'Casi siempre', quest: 'D.3.1' },
      { id: 2, name: 'Algunas veces', quest: 'D.3.1' },
      { id: 1, name: 'No sé', quest: 'D.3.1' },
      { id: 0, name: 'No se hace', quest: 'D.3.1' },
    ],
  },
  {
    id: 'D.3.2',
    idIndex: 44,
    text: 'En la institución educativa la Asamblea y Consejo de Padres cuenta con la participación de familias de estudiantes en situación de vulnerabilidad que aportan a la evaluación y definición de acciones inclusivas.',
    options: [
      { id: 4, name: 'Siempre', quest: 'D.3.2' },
      { id: 3, name: 'Casi siempre', quest: 'D.3.2' },
      { id: 2, name: 'Algunas veces', quest: 'D.3.2' },
      { id: 1, name: 'No sé', quest: 'D.3.2' },
      { id: 0, name: 'No se hace', quest: 'D.3.2' },
    ],
  },
  {
    id: 'D.3.3',
    idIndex: 45,
    text: 'En la institución educativa se desarrollan propuestas de programas de apoyo familia a familia  para fortalecer las habilidades colaborativas entre ellas.',
    options: [
      { id: 4, name: 'Siempre', quest: 'D.3.3' },
      { id: 3, name: 'Casi siempre', quest: 'D.3.3' },
      { id: 2, name: 'Algunas veces', quest: 'D.3.3' },
      { id: 1, name: 'No sé', quest: 'D.3.3' },
      { id: 0, name: 'No se hace', quest: 'D.3.3' },
    ],
  },
  {
    id: 'D.4.1',
    idIndex: 46,
    text: 'En la institución educativa se realizan acciones comprensibles para cada uno de los estudiantes con el fin de prevenir accidentes y enfermedades.',
    options: [
      { id: 4, name: 'Siempre', quest: 'D.4.1' },
      { id: 3, name: 'Casi siempre', quest: 'D.4.1' },
      { id: 2, name: 'Algunas veces', quest: 'D.4.1' },
      { id: 1, name: 'No sé', quest: 'D.4.1' },
      { id: 0, name: 'No se hace', quest: 'D.4.1' },
    ],
  },
  {
    id: 'D.4.2',
    idIndex: 47,
    text: 'En la institución educativa se realizan acciones comprensibles para prevenir la  drogadicción, el alcoholismo, las enfermedades de transmisión sexual, el abuso sexual, el maltrato físico y verbal, entre otras, que pueden afectar a todos los estudiantes.',
    options: [
      { id: 4, name: 'Siempre', quest: 'D.4.2' },
      { id: 3, name: 'Casi siempre', quest: 'D.4.2' },
      { id: 2, name: 'Algunas veces', quest: 'D.4.2' },
      { id: 1, name: 'No sé', quest: 'D.4.2' },
      { id: 0, name: 'No se hace', quest: 'D.4.2' },
    ],
  },
  {
    id: 'D.4.3',
    idIndex: 48,
    text: 'En la institución educativa se realizan actividades de entrenamiento para que todas las personas, incluso las que presentan limitaciones, aprendan qué hacer en caso de desastres como: incendio, terremoto, inundación, entre otros.',
    options: [
      { id: 4, name: 'Siempre', quest: 'D.4.3' },
      { id: 3, name: 'Casi siempre', quest: 'D.4.3' },
      { id: 2, name: 'Algunas veces', quest: 'D.4.3' },
      { id: 1, name: 'No sé', quest: 'D.4.3' },
      { id: 0, name: 'No se hace', quest: 'D.4.3' },
    ],
  },
];
