export const list = [
  {
    proceso: 'A5: Clima Escolar',
    area: 'Area A: Gestión Directiva',
    directivo: '3.26',
    otros: '3.15',
    docente: '3.18',
    estudiante: '3.33',
    padreDeFamilia: '3,40',
    personalDeApoyo: '3.40',
    promedioDelProceso: '3.17',
  },
  {
    proceso: 'A2 - Gerencia Estratégica	',
    area: 'Area A: Gestión Directiva',
    directivo: '3.09',
    otros: '3.11',
    docente: '3.16',
    estudiante: '3.13',
    padreDeFamilia: '3,26',
    personalDeApoyo: '3.00',
    promedioDelProceso: '3.13',
  },
  {
    proceso: 'A1: Direccionamiento estratégico',
    area: 'Area B: Gestión Académica',
    directivo: '3.26',
    otros: '3.15',
    docente: '3.18',
    estudiante: '3.33',
    padreDeFamilia: '3,40',
    personalDeApoyo: '3.40',
    promedioDelProceso: '3.17',
  },
  {
    proceso: 'A3: Gobierno Escolar',
    area: 'ÁREA A: GESTIÓN DIRECTIVA',
    directivo: '3,28',
    otros: '3.20',
    docente: '3.26',
    estudiante: '3.33',
    padreDeFamilia: '3,40',
    personalDeApoyo: '3.33',
    promedioDelProceso: '3.23',
  },
];

export const list2 = [
  {
    area: 'ÁREA A: GESTIÓN DIRECTIVA',
    directivo: '3.26',
    otros: '3.15',
    docente: '3.18',
    estudiante: '3.33',
    padreDeFamilia: '3,40',
    personalDeApoyo: '3.40',
    promedio: '3.17',
  },
  {
    area: 'ÁREA B: GESTIÓN ACADÉMICA',
    directivo: '3.15',
    otros: '2.91',
    docente: '2.94',
    estudiante: '3.33',
    padreDeFamilia: '3,40',
    personalDeApoyo: '3.40',
    promedio: '2.93',
  },
  {
    area: 'ÁREA C: GESTIÓN ADMINISTRATIVA',
    directivo: '3.06',
    otros: '2.94',
    docente: '3.06',
    estudiante: '2.98',
    padreDeFamilia: '3,06',
    personalDeApoyo: '2.39',
    promedio: '3.00',
  },
  {
    area: 'ÁREA D: GESTIÓN ADMINISTRATIVA',
    directivo: '3.03',
    otros: '2.81',
    docente: '2.87',
    estudiante: '3.18',
    padreDeFamilia: '3,19',
    personalDeApoyo: '3.40',
    promedio: '2.84',
  },
];
export const list3 = [
  {
    proceso: 'ÁREA A: GESTIÓN DIRECTIVA',
    area: '3',
    directivo: '0',
    otros: '3.40',
    docente: '3.40',
    estudiante: '3.17',
  },
  {
    proceso: 'ÁREA B: GESTIÓN ACADÉMICA',
    area: '3',
    directivo: '0',
    otros: '3.40',
    docente: '3.40',
    estudiante: '3.17',
  },
  {
    proceso: 'ÁREA C: GESTIÓN ADMINISTRATIVA',
    area: '3',
    directivo: '0',
    otros: '3.40',
    docente: '3.40',
    estudiante: '3.17',
  },
];
export const list4 = [
  {
    proceso: 'A5: Clima Escolar',
    area: '3',
    directivo: '1',
    otros: '3',
    docente: '3',
    estudiante: '19',
  },
  {
    proceso: 'A1: Direccionamiento estratégico',
    area: '4',
    directivo: '0',
    otros: '4',
    docente: '4',
    estudiante: '13',
  },
  {
    proceso: 'A2 - Gerencia Estratégica	',
    area: '3',
    directivo: '1',
    otros: '3',
    docente: '3',
    estudiante: '23',
  },
  {
    proceso: 'A3: Gobierno Escolar',
    area: '3',
    directivo: '1',
    otros: '3',
    docente: '3',
    estudiante: '21',
  },
  {
    proceso: 'A4: Cultura Institucional',
    area: '3',
    directivo: '1',
    otros: '3',
    docente: '3',
    estudiante: '23',
  },
  {
    proceso: 'A6: Relaciones con el entorno',
    area: '3',
    directivo: '1',
    otros: '3',
    docente: '3',
    estudiante: '31',
  },
];
export const list5 = [
  {
    proceso: 'A 1.1',
    area: 'A1: Direccionamiento estratégico',
    directivo: '4',
    otros: '0',
    docente: '4',
    estudiante: '4',
    padreDeFamilia: '12',
  },
  {
    proceso: 'A.1.2',
    area: 'A1: Direccionamiento estratégico',
    directivo: '4',
    otros: '0',
    docente: '4',
    estudiante: '4',
    padreDeFamilia: '11',
  },
  {
    proceso: 'A.1.3',
    area: 'A1: Direccionamiento estratégico',
    directivo: '4',
    otros: '0',
    docente: '4',
    estudiante: '4',
    padreDeFamilia: '15',
  },
  {
    proceso: 'A.2.1',
    area: 'A2 - Gerencia Estratégica',
    directivo: '3',
    otros: '1',
    docente: '3',
    estudiante: '3',
    padreDeFamilia: '21',
  },
];
export const colNames = [
  'Proceso',
  'Área',
  'Directivo',
  'Otros',
  'Docente',
  'Estudiante',
  'Padre de familia',
  'Personal de apoyo',
  'Promedio del área',
];

export const colNames2 = [
  'Área',
  'Directivo',
  'Otros',
  'Docente',
  'Estudiante',
  'Padre de familia',
  'Personal de apoyo',
  'Promedio del área',
];

export const colNames3 = [
  'Área',
  'Media aritmética',
  'Desviación estandar',
  'Limite inferior',
  'Limite superior',
  'Coeficiente de variación',
];

export const colNames4 = [
  'Proceso',
  'Media aritmética',
  'Desviación estandar',
  'Limite inferior',
  'Limite superior',
  'Coeficiente de variación',
];

export const colNames5 = [
  'Variable',
  'Proceso',
  'Media aritmética',
  'Desviación estandar',
  'Limite inferior',
  'Limite superior',
  'Coeficiente de variación',
];

export const listContentDashboard = [
  { id: 0, name: 'Indice de Inclusión', state: true },
  { id: 1, name: 'Resumen del índice de inclusión institucional por área', state: true },
  { id: 2, name: 'Resumen del índice institucional por proceso', state: true },
  { id: 3, name: 'Gráfico Indice de Inclusión por estamento', state: true },
  { id: 4, name: 'Gráfico Indice de Inclusión por área', state: true },
  { id: 5, name: 'Totales por área', state: true },
  { id: 6, name: 'Totales por proceso', state: true },
  { id: 7, name: 'Totales por variables', state: true },
  { id: 8, name: 'Interpretación por áreas', state: true },
];

export const listContentDashboardDefault = [
  { id: 0, name: 'Indice de Inclusión', state: true },
  { id: 1, name: 'Resumen del índice de inclusión institucional por área', state: true },
  { id: 2, name: 'Resumen del índice institucional por proceso', state: true },
  { id: 3, name: 'Gráfico Indice de Inclusión por estamento', state: true },
  { id: 4, name: 'Gráfico Indice de Inclusión por área', state: true },
  { id: 5, name: 'Totales por área', state: true },
  { id: 6, name: 'Totales por proceso', state: true },
  { id: 7, name: 'Totales por variables', state: true },
  { id: 8, name: 'Interpretación por áreas', state: true },
];
